/*
 * Сервис приема сообщений о проблемах
 * Здесь описаны методы сервиса приема сообщений о проблемах
 *
 * OpenAPI spec version: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.Comment;
import io.swagger.client.model.HistoryStatus;
import io.swagger.client.model.Location;
import io.swagger.client.model.Person;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Complaint
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-06-22T08:36:37.564Z[GMT]")public class Complaint {

  @SerializedName("id")
  private Long id = null;

  @SerializedName("categoryId")
  private Long categoryId = null;

  @SerializedName("category")
  private String category = null;

  @SerializedName("dangerLevel")
  private Integer dangerLevel = null;

  @SerializedName("title")
  private String title = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("location")
  private Location location = null;

  @SerializedName("complaintTimestamp")
  private String complaintTimestamp = null;

  @SerializedName("creationTimestamp")
  private String creationTimestamp = null;

  @SerializedName("fileLink")
  private List<String> fileLink = null;

  @SerializedName("person")
  private Person person = null;

  @SerializedName("userId")
  private Long userId = null;

  @SerializedName("likes")
  private Integer likes = null;

  @SerializedName("comments")
  private List<Comment> comments = null;

  @SerializedName("status")
  private Integer status = null;

  @SerializedName("visible")
  private Boolean visible = null;

  @SerializedName("anonymous")
  private Boolean anonymous = null;

  @SerializedName("history")
  private List<HistoryStatus> history = null;
  public Complaint id(Long id) {
    this.id = id;
    return this;
  }

  

  /**
  * Get id
  * minimum: 0
  * @return id
  **/
  @Schema(required = true, description = "")
  public Long getId() {
    return id;
  }
  public void setId(Long id) {
    this.id = id;
  }
  public Complaint categoryId(Long categoryId) {
    this.categoryId = categoryId;
    return this;
  }

  

  /**
  * Get categoryId
  * minimum: 0
  * @return categoryId
  **/
  @Schema(description = "")
  public Long getCategoryId() {
    return categoryId;
  }
  public void setCategoryId(Long categoryId) {
    this.categoryId = categoryId;
  }
  public Complaint category(String category) {
    this.category = category;
    return this;
  }

  

  /**
  * Get category
  * @return category
  **/
  @Schema(required = true, description = "")
  public String getCategory() {
    return category;
  }
  public void setCategory(String category) {
    this.category = category;
  }
  public Complaint dangerLevel(Integer dangerLevel) {
    this.dangerLevel = dangerLevel;
    return this;
  }

  

  /**
  * Get dangerLevel
  * minimum: 1
  * maximum: 10
  * @return dangerLevel
  **/
  @Schema(required = true, description = "")
  public Integer getDangerLevel() {
    return dangerLevel;
  }
  public void setDangerLevel(Integer dangerLevel) {
    this.dangerLevel = dangerLevel;
  }
  public Complaint title(String title) {
    this.title = title;
    return this;
  }

  

  /**
  * Get title
  * @return title
  **/
  @Schema(required = true, description = "")
  public String getTitle() {
    return title;
  }
  public void setTitle(String title) {
    this.title = title;
  }
  public Complaint description(String description) {
    this.description = description;
    return this;
  }

  

  /**
  * Get description
  * @return description
  **/
  @Schema(required = true, description = "")
  public String getDescription() {
    return description;
  }
  public void setDescription(String description) {
    this.description = description;
  }
  public Complaint location(Location location) {
    this.location = location;
    return this;
  }

  

  /**
  * Get location
  * @return location
  **/
  @Schema(description = "")
  public Location getLocation() {
    return location;
  }
  public void setLocation(Location location) {
    this.location = location;
  }
  public Complaint complaintTimestamp(String complaintTimestamp) {
    this.complaintTimestamp = complaintTimestamp;
    return this;
  }

  

  /**
  * Дата проблемы
  * @return complaintTimestamp
  **/
  @Schema(description = "Дата проблемы")
  public String getComplaintTimestamp() {
    return complaintTimestamp;
  }
  public void setComplaintTimestamp(String complaintTimestamp) {
    this.complaintTimestamp = complaintTimestamp;
  }
  public Complaint creationTimestamp(String creationTimestamp) {
    this.creationTimestamp = creationTimestamp;
    return this;
  }

  

  /**
  * Дата создания проблемы
  * @return creationTimestamp
  **/
  @Schema(description = "Дата создания проблемы")
  public String getCreationTimestamp() {
    return creationTimestamp;
  }
  public void setCreationTimestamp(String creationTimestamp) {
    this.creationTimestamp = creationTimestamp;
  }
  public Complaint fileLink(List<String> fileLink) {
    this.fileLink = fileLink;
    return this;
  }

  public Complaint addFileLinkItem(String fileLinkItem) {
    if (this.fileLink == null) {
      this.fileLink = new ArrayList<String>();
    }
    this.fileLink.add(fileLinkItem);
    return this;
  }

  /**
  * Get fileLink
  * @return fileLink
  **/
  @Schema(description = "")
  public List<String> getFileLink() {
    return fileLink;
  }
  public void setFileLink(List<String> fileLink) {
    this.fileLink = fileLink;
  }
  public Complaint person(Person person) {
    this.person = person;
    return this;
  }

  

  /**
  * Get person
  * @return person
  **/
  @Schema(description = "")
  public Person getPerson() {
    return person;
  }
  public void setPerson(Person person) {
    this.person = person;
  }
  public Complaint userId(Long userId) {
    this.userId = userId;
    return this;
  }

  

  /**
  * Get userId
  * minimum: 0
  * @return userId
  **/
  @Schema(required = true, description = "")
  public Long getUserId() {
    return userId;
  }
  public void setUserId(Long userId) {
    this.userId = userId;
  }
  public Complaint likes(Integer likes) {
    this.likes = likes;
    return this;
  }

  

  /**
  * Get likes
  * @return likes
  **/
  @Schema(description = "")
  public Integer getLikes() {
    return likes;
  }
  public void setLikes(Integer likes) {
    this.likes = likes;
  }
  public Complaint comments(List<Comment> comments) {
    this.comments = comments;
    return this;
  }

  public Complaint addCommentsItem(Comment commentsItem) {
    if (this.comments == null) {
      this.comments = new ArrayList<Comment>();
    }
    this.comments.add(commentsItem);
    return this;
  }

  /**
  * Get comments
  * @return comments
  **/
  @Schema(description = "")
  public List<Comment> getComments() {
    return comments;
  }
  public void setComments(List<Comment> comments) {
    this.comments = comments;
  }
  public Complaint status(Integer status) {
    this.status = status;
    return this;
  }

  

  /**
  * Номер шага, который должен быть заполнен на форме следующим
  * @return status
  **/
  @Schema(description = "Номер шага, который должен быть заполнен на форме следующим")
  public Integer getStatus() {
    return status;
  }
  public void setStatus(Integer status) {
    this.status = status;
  }
  public Complaint visible(Boolean visible) {
    this.visible = visible;
    return this;
  }

  

  /**
  * Get visible
  * @return visible
  **/
  @Schema(description = "")
  public Boolean isVisible() {
    return visible;
  }
  public void setVisible(Boolean visible) {
    this.visible = visible;
  }
  public Complaint anonymous(Boolean anonymous) {
    this.anonymous = anonymous;
    return this;
  }

  

  /**
  * Get anonymous
  * @return anonymous
  **/
  @Schema(description = "")
  public Boolean isAnonymous() {
    return anonymous;
  }
  public void setAnonymous(Boolean anonymous) {
    this.anonymous = anonymous;
  }
  public Complaint history(List<HistoryStatus> history) {
    this.history = history;
    return this;
  }

  public Complaint addHistoryItem(HistoryStatus historyItem) {
    if (this.history == null) {
      this.history = new ArrayList<HistoryStatus>();
    }
    this.history.add(historyItem);
    return this;
  }

  /**
  * Get history
  * @return history
  **/
  @Schema(description = "")
  public List<HistoryStatus> getHistory() {
    return history;
  }
  public void setHistory(List<HistoryStatus> history) {
    this.history = history;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Complaint complaint = (Complaint) o;
    return Objects.equals(this.id, complaint.id) &&
        Objects.equals(this.categoryId, complaint.categoryId) &&
        Objects.equals(this.category, complaint.category) &&
        Objects.equals(this.dangerLevel, complaint.dangerLevel) &&
        Objects.equals(this.title, complaint.title) &&
        Objects.equals(this.description, complaint.description) &&
        Objects.equals(this.location, complaint.location) &&
        Objects.equals(this.complaintTimestamp, complaint.complaintTimestamp) &&
        Objects.equals(this.creationTimestamp, complaint.creationTimestamp) &&
        Objects.equals(this.fileLink, complaint.fileLink) &&
        Objects.equals(this.person, complaint.person) &&
        Objects.equals(this.userId, complaint.userId) &&
        Objects.equals(this.likes, complaint.likes) &&
        Objects.equals(this.comments, complaint.comments) &&
        Objects.equals(this.status, complaint.status) &&
        Objects.equals(this.visible, complaint.visible) &&
        Objects.equals(this.anonymous, complaint.anonymous) &&
        Objects.equals(this.history, complaint.history);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(id, categoryId, category, dangerLevel, title, description, location, complaintTimestamp, creationTimestamp, fileLink, person, userId, likes, comments, status, visible, anonymous, history);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Complaint {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    categoryId: ").append(toIndentedString(categoryId)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    dangerLevel: ").append(toIndentedString(dangerLevel)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    complaintTimestamp: ").append(toIndentedString(complaintTimestamp)).append("\n");
    sb.append("    creationTimestamp: ").append(toIndentedString(creationTimestamp)).append("\n");
    sb.append("    fileLink: ").append(toIndentedString(fileLink)).append("\n");
    sb.append("    person: ").append(toIndentedString(person)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    likes: ").append(toIndentedString(likes)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    visible: ").append(toIndentedString(visible)).append("\n");
    sb.append("    anonymous: ").append(toIndentedString(anonymous)).append("\n");
    sb.append("    history: ").append(toIndentedString(history)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
